### ISSUE TITLE
Add alt attributes

### ISSUE THREAD

**Issue by y10987** [gkrishna321/prj-rev-bwfs-dasmoto#2]
Add alt attributes to your image element

https://github.com/gkrishna321/prj-rev-bwfs-dasmoto/blob/5d0191d55b9c0d0b928ee44463272549655bdec1/DasmotosArtAndCrafts/index.html#L19

**Comment by gkrishna321** [comment]
Indeed I see the value in adding alternative text attributes in html. Thanks for the suggestion.
